
[project]
  description = "Framework for packaging CAD models"
  dynamic = ["dependencies"]
  keywords = ["cadquery", "build123d"]
  name = "partcad"
  readme = "README.md"
  requires-python = ">=3.10"
  version = "0.1.1"

  [[project.authors]]
    email = "openvmp@proton.me"
    name = "Roman Kuzmenko"

  [project.license]
    file = "LICENSE.txt"

  [[project.maintainers]]
    email = "openvmp@proton.me"
    name = "Roman Kuzmenko"

  [project.scripts]
    pc = "partcad:main_cli"

[tool]

  [tool.pytest]

    [tool.pytest.ini_options]
      pythonpath = "src"

  [tool.setuptools]

    [tool.setuptools.dynamic]

      [tool.setuptools.dynamic.dependencies]
        file = ["requirements.txt"]

    [tool.setuptools.package-data]
      "partcad.template" = ["*.yaml"]
